# Generated by Django 2.2.2 on 2019-06-19 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mazix_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('category', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mazix_api.Category')),
            ],
        ),
    ]
