# Generated by Django 2.2.2 on 2019-06-19 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mazix_api', '0002_auto_20190619_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='mazix_api.Category'),
        ),
    ]
