# Generated by Django 2.2.2 on 2019-06-22 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mazix_api', '0003_auto_20190619_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
